package ua.cn.stu.navigation.persistence.preference


object PreferenceKeys {
  const val TYPE_CELLS_LIST_MAIN = "TYPE_CELLS_LIST_MAIN"
  const val MASSAGES_LIST_MAIN = "MASSAGES_LIST_MAIN"
  const val TIMESTAMPS_LIST_MAIN = "TIMESTAMPS_LIST_MAIN"

  const val DEVICE_NAME = "DEVICE_NAME"
  const val DEVICE_ADDR = "DEVICE_ADDR"
  const val APP_PREFERENCES = "APP_PREFERENCES"
  const val NEW_KEY = "HGBKHUBYHKFGYGJHBKJVGUIYTKHDCYFG"
  const val NEW_KEY2 = "HGBKHUBYH2KFGYGJHBKJVGUIYTKHDCYFG"
  const val NEW_KEY3 = "HGBKHUBYH23KFGYGJHBKJVGUIYTKHDCYFG"
  const val TEST_SAVE = "TEST_SAVE"

  const val TIMESTAMP_LAST_READ_LOG = "TIMESTAMP_LAST_READ_LOG"
  const val TIMESTAMP_LAST_LOG_MASSAGE = "TIMESTAMP_LAST_LOG_MASSAGE"

  const val ATTEMPTS_TO_UN_LOCK = "ATTEMPTS_TO_UN_LOCK"
  const val CONNECTION_PASSWORD = "CONNECTION_PASSWORD"
  const val CONNECTED_DEVICE = "CONNECTED_DEVICE"
  const val LAST_CONNECTED_DEVICE_ADDRESS = "LAST_CONNECTED_DEVICE_ADDRESS"
  const val CONNECTED_DEVICE_ADDRESS = "CONNECTED_DEVICE_ADDRESS"
  const val ACTIVATE_PIN_CODE_APP = "ACTIVATE_PIN_CODE_APP"
  const val PIN_CODE_APP = "PIN_CODE_APP"
  const val ACTIVATE_PIN_CODE_SETTINGS = "ACTIVATE_PIN_CODE_SETTINGS"
  const val PIN_CODE_SETTINGS = "PIN_CODE_SETTINGS"
  const val ACTIVATE_STEP_BOLUS = "ACTIVATE_STEP_BOLUS"
  const val ACTIVATE_EXTENDED_BOLUS = "ACTIVATE_EXTENDED_BOLUS"
  const val ACTIVATE_DUAL_PATTERN_BOLUS = "ACTIVATE_DUAL_PATTERN_BOLUS"
  const val ACTIVATE_SUPER_BOLUS = "ACTIVATE_SUPER_BOLUS"

  const val SELECTED_PROFILE = "SELECTED_PROFILE"
  const val PROFILE_NAMES = "PROFILE_NAMES"
  const val DATA_ALL_CHARTS = "DATA_ALL_CHARTS"
  const val PERIOD_NAMES_MAIN = "PERIOD_NAMES_MAIN"
  const val START_TIME_ALL_PERIODS_MAIN = "START_TIME_ALL_PERIODS_MAIN"
  const val INPUT_SPEED_ALL_PERIODS_MAIN = "INPUT_SPEED_ALL_PERIODS_MAIN"


}